security:
  jwt:
    key-store: classpath:tosantechno-secretkey.jks
    key-store-password: Tosan123@
    key-pair-alias: tosantechnokkey
    key-pair-password: tosantechno-secretpass
server:
  port: 9000

spring:
  application:
    name: aaserver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true

  datasource:
    initialization-mode: always
    platform: postgres
    url: jdbc:postgresql://localhost:5432/testdb
    username: postgres
    password: s$cret
